version: '3.8'

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    networks:
      - nextcloud_net
    volumes:
      - nextcloud:/var/www/html
      - /mnt/storage/nextcloud_data:/var/www/html/data
    environment:
      - MYSQL_HOST=nextcloud_db
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}

  nextcloud_db:
    image: mariadb:10.6
    container_name: nextcloud_db
    restart: unless-stopped
    networks:
      - nextcloud_net
    volumes:
      - nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    networks:
      - nextcloud_net
    volumes:
      - ${CLOUDFLARED_CREDENTIALS_FILE}:/etc/cloudflared/creds.json
    command: tunnel run --url http://nextcloud:80
    environment:
      - TUNNEL_ID=${CLOUDFLARED_TUNNEL_ID}

volumes:
  nextcloud:
    driver: local
  nextcloud_db:
    driver: local

networks:
  nextcloud_net:
    driver: bridge

