Copy

version: '3.8'

services:
  nextcloud:
    image: nextcloud:latest
    networks:
      - bahut_net
    volumes:
      - nextcloud:/var/www/html
      - /mnt/storage/nextcloud_data:/var/www/html/data
    environment:
      - MYSQL_HOST=nextcloud_db
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  nextcloud_db:
    image: mariadb:10.6
    networks:
      - bahut_net
    volumes:
      - nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  tailscale:
    image: tailscale/tailscale
    networks:
      - bahut_net
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/lib/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTH_KEY}

volumes:
  nextcloud:
  nextcloud_db:

networks:
  bahut_net:
    driver: bridge
